kind: Service                             
apiVersion: v1
metadata:
  name: dk12Website
  labels:
    app: dk12Website
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: dk12Website                  
  type: LoadBalancer               