kind: Service
apiVersion: v1
metadata:
  name: dk12website
  labels:
    app: dk12Website
spec:
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31200
  selector:
    app: dk12website
  externalIPs:
   - 130.61.110.179
  type: LoadBalancer