kind: Service
apiVersion: v1
metadata:
  name: dk12website
  labels:
    app: dk12Website
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 32100
  selector:
    app: dk12website
  type: LoadBalancer