kind: Service                             
apiVersion: v1
metadata:
  name: dk12website
  labels:
    app: dk12Website
spec:
  ports:
    - protocol: TCP
      port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: dk12website   
  LoadBalancerIP: 130.61.110.179               
  type: LoadBalancer               